### ISSUE TITLE
Questions about chaskiq

### ISSUE THREAD

**Issue by tabrza** [chaskiq/chaskiq#293]
hi @michelson - I'm hoping to take this live in the next few days but have some questions that i would really appreciate help with!

1. how does the help center setup work
2. what does hidden constraints mean in campaigns?
3. how do mailing campaigns work?
4. how do in app message campaigns work? would banners appear on the widget? how do we trigger them?
5. When creating rules, and adding filters, the 'missing value' filter appears. How does that work?
6. how can a bot be triggered to send a message to the user as soon as they land on the website instead of the user needing to send an initial message to the widget?
7. how do assignment rules work? is it possible to assign teams to conversations instead of single users in assignment rules/bot handover?
8. conversation number doesn't show correctly.. how are they filtered? even including open/closed
9. is it possible to highlight the tab or something like with fb messenger to show a new chat or number of chats available in order to avoid missed chat?
10. How can whatsapp be connected so that messages are sent to a whatsapp business account?
11. How can slack be integrated?
12. Unable to upload logo/user image. Don't get an error in the heroku console either.. Have you encountered this issue before?
13. With always ask user for email address before starting conversation, it does not require this on the front end. is it possible to do this wiht a phone number as an alternative?
14. in the bot section, ask for contact details if the app doesn't have the email address or phone number doesn't exist only works in default behaviour
15. unable to uncheck: Leave a 2 minute delay before triggering Task Bots during office hours button under for users tab

**Comment by michelson** [comment]
how does the help center setup work

> help center live in a subdomain, you set a subdomain in domain settings and all your articles will be displayed on it

what does hidden constraints mean in campaigns?

> hidden constraints are a way for chaskiq to know for when to deliver a message, so if you set , constraints on "open" then the message will be delivered until the user open it. or will be sent until it closes if you set constraints on close

how do mailing campaigns work?

> you configure them , then you send them :D . can you be more precise ? is there something you did not understand ? I think -i have to do some better documentation

how do in app message campaigns work? would banners appear on the widget? how do we trigger them?

When creating rules, and adding filters, the 'missing value' filter appears. How does that work?

> yes, you may need to click on it and add the value

how can a bot be triggered to send a message to the user as soon as they land on the website instead of the user needing to send an initial message to the widget?

> yes, use bots flows they will be triggered proactively

how do assignment rules work? is it possible to assign teams to conversations instead of single users in assignment rules/bot handover?

> no teams support yet

conversation number doesn't show correctly.. how are they filtered? even including open/closed
is it possible to highlight the tab or something like with fb messenger to show a new chat or number of chats available in order to avoid missed chat?
> would be possible

How can whatsapp be connected so that messages are sent to a whatsapp business account?

> you can use twillio, vinage, dialog360 o message bird. check the integrations section on app settings

How can slack be integrated?

> you have to setup a slack app from your side., to link the app you will need to add the app credentials on app settings integrations

Unable to upload logo/user image. Don't get an error in the heroku console either.. Have you encountered this issue before?
> probably you haven't set up the AWS credentials

With always ask user for email address before starting conversation, it does not require this on the front end. is it possible to do this wiht a phone number as an alternative?

> you could setup your own behaviors from bots, and you can use the chaskiq apps "qualifier"

in the bot section, ask for contact details if the app doesn't have the email address or phone number doesn't exist only works in default behaviour
unable to uncheck: Leave a 2 minute delay before triggering Task Bots during office hours button under for users tab
> bug!
