### ISSUE TITLE
What is used for the field "properties: { }" in the chat widget?

### ISSUE THREAD

**Issue by gabrieletassoni** [chaskiq/chaskiq#369]
Hi,
I'm starting to implement the new version of the chat, in the data key I see a `properties: {}` field of type object, what can be used for? Which keys it accepts? Where are the keys accepted in the `properties: {}` object visualized/used in the backend?

```javascript
      <script>
        (function(d,t) {
          var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
          g.src="https://chat.deventa.io/embed.js"
          s.parentNode.insertBefore(g,s);
          g.onload=function(){
            new window.ChaskiqMessengerEncrypted({
              domain: 'https://chat.deventa.io',
              ws:  'wss://chat.deventa.io/cable',
              app_id: "RQWaCmihfArXXJcCBTtYFMsF",
              data: {
                email: "user@email.com",
                identifier_key: "INSERT_HMAC_VALUE_HERE",
                properties: { }
              },
              lang: "USER_LANG_OR_DEFAULTS_TO_BROWSER_LANG" 
            })
          }
        })(document,"script");
      </script>
```

Thank you for the documentation.

**Comment by michelson** [comment]
hi , you can add whatever you like in the properties field but in order to use them in the chaskiq panel you will need to configure them on the user data section on app settings in order to use them on the user segments, filters , etc ...

![image](https://user-images.githubusercontent.com/11976/115731060-d3bea880-a354-11eb-8ca3-635a1ddbda98.png)

**Comment by gabrieletassoni** [comment]
Hi, ok, clear, thanks for the clarification.
