### ISSUE TITLE
Use releases version in docker images

### ISSUE THREAD

**Issue by jalberto** [chaskiq/chaskiq#686]
**Is your feature request related to a problem? Please describe.**
I am always frustrated when the official container/image versioning doesn't follow the same versions as the code releases.

**Describe the solution you'd like**
I will love if the container/docker image uses same versions as the releases in GH 

**Additional context**
for CI/CD and for sanity, it is important not to use the `latest` tag in production and be able to check which release is running

**Comment by michelson** [comment]
Hi, I agree with this, 
How it works right now is the generation of 2 releases per merge on the "master" branch. A "latest" tag and a tag based on the commit SHA. That way, we can release often. I agree that It will also be a good idea to add a docker build based on the latest tag.
Would you be interested in contributing the fix for this?

**Comment by jalberto** [comment]
Yes, I can get to it in few days 😊
